### PR TITLE
Client cant kill on not connect

### PR DESCRIPTION
**Pull request by bariscodefxy**

### CODE REVIEW

**Comment by a1batross** [comment]
That's actually a good note.

But can you just port https://github.com/FWGS/xash3d/commit/de8ab25ca0bd8a9882d4a1859235e7f08d020b4d from old engine? Your patch needs an edict check and a better error message would be nice too.

**Comment by bariscodefxy** [comment]
> That's actually a good note.
> 
> But can you just port [FWGS/xash3d@de8ab25](https://github.com/FWGS/xash3d/commit/de8ab25ca0bd8a9882d4a1859235e7f08d020b4d) from old engine? Your patch needs an edict check and a better error message would be nice too.

No i already know this bug i tried this on my xash server

**Comment by bariscodefxy** [comment]
> That's actually a good note.
> 
> But can you just port [FWGS/xash3d@de8ab25](https://github.com/FWGS/xash3d/commit/de8ab25ca0bd8a9882d4a1859235e7f08d020b4d) from old engine? Your patch needs an edict check and a better error message would be nice too.

Now good?

**Comment by bariscodefxy** [comment]
> That's actually a good note.
> 
> But can you just port [FWGS/xash3d@de8ab25](https://github.com/FWGS/xash3d/commit/de8ab25ca0bd8a9882d4a1859235e7f08d020b4d) from old engine? Your patch needs an edict check and a better error message would be nice too.

Now ok?

**Comment by a1batross** [comment]
Merged, thanks.

Please, next time, follow our conribution guidelines in CONTRIBUTING.md

**Pull request merged**
