### PR TITLE
Introduce bug-compatibility levels

### PR DESCRIPTION
**Pull request by a1batross**
* for now we only have GoldSrc bug compatibility, can be used for
  games that require precise GoldSrc behaviour, like CSCZDS
* enabled with -bugcomp command line

### CODE REVIEW

**Comment by a1batross** [comment]
Obligatory "pls review"

cc @nekonomicon @mittorn @SNMetamorph

**Comment by SNMetamorph** [comment]
Looks good to me

**Comment by nekonomicon** [comment]
LGTM.

**Comment by a1batross** [comment]
Changed wording in documentation a bit.

cc @nekonomicon @SNMetamorph needs proofreading

**Comment by SNMetamorph** [comment]
I think it's ok

**Comment by nekonomicon** [comment]
All good.

**Pull request merged**
