### PR TITLE
engine: ref: try to bruteforce all available renderers if we're failed to load requested one

### PR DESCRIPTION
**Pull request by a1batross**
@glebm can you try this patch if #247 got fixed?

### CODE REVIEW

**Comment by glebm** [comment]
Thanks!

Looks like this should work (will test later).
It does seem a bit wasteful to try to open a renderer which may not exist.

Perhaps we should merge both this and #257?

**Comment by a1batross** [comment]
> It does seem a bit wasteful to try to open a renderer which may not exist.

We reuse the list that was acquired during CollectRendererNames. It will not try to load something that doesn't exist twice.

**Comment by glebm** [comment]
On line 670 `refopt` would usually be the `DEFAULT_ACCELERATED_RENDERER` (unless `-ref` is passed on the command line)

**Comment by a1batross** [comment]
Ah I see. 

I don't see any problem in this to be honest. So, will dlopen() return NULL, is this a big issue?

**Comment by glebm** [comment]
Not a big deal just makes the log a bit noisy

If we don't want the default to be confiurable, perhaps we should get rid of `DEFAULT_ACCELERATED_RENDERER` entirely?

Then we can just call the first detected renderer (or `ref` if given).

**Review by glebm — APPROVED** [review]

**Comment by a1batross** [comment]
Yep, it must be removed. We can use first available then, as we already listed them by the precendence.

**Pull request merged**
