### PR TITLE
Gamma and overbright

### LINKED ISSUE #1249: Overbrights
https://github.com/FWGS/xash3d/issues/181

@a1batross, what's happened to gl_overbright? It's absent in this fork and r_lighting_modulate does not give the same effect.

### PR DESCRIPTION
**Pull request by a1batross**
SourceHut thread: https://lists.sr.ht/~a1batross/xash3d-fwgs/patches/48370

In this patchset I tried to mimic original GoldSrc rendering as much accurately as possible. It also adds overbrights rendering (without gl_vbo yet).

Compared to other gamma & overbrights attempts, I reverse-engineered the original gamma table generation function and how the gamma tables are being applied to the textures and lightmaps.

The result is nearly indistinguishable from original Half-Life 1.
I also tried to compare the images with ImageMagick and while it finds some exact pixels, most of the screenshots are pure noise and depend on too many variables in the rendering process.

Fixes #1249 #694

### CODE REVIEW

**Comment by a1batross** [comment]
* `brightness` is broken with `gl_overbright 0`

**Comment by SNMetamorph** [comment]
Tested this in PrimeXT and it looks like that there is no issues with texture gamma convertion, good.

**Comment by a1batross** [comment]
I've been also playing with this, seems fine.

**Comment by a1batross** [comment]
Applied.

**Pull request closed without merging**
