### PR TITLE
utils: mdldec: smd.c: fix linear movement loss.

### PR DESCRIPTION
**Pull request by nekonomicon**
Must fix https://github.com/FWGS/xash3d-fwgs/issues/1444
This code is similar to https://github.com/ZeqMacaw/Crowbar/blob/master/Crowbar/Core/GameModel/SourceModel10/SourceSmdFile10.vb#L125
@SNMetamorph please test.

### CODE REVIEW

**Comment by a1batross** [comment]
Is this ready to merge?

**Comment by nekonomicon** [comment]
Nope.

**Comment by SNMetamorph** [comment]
This fix is working. LGTM.

**Comment by nekonomicon** [comment]
Ready to merge then.

**Pull request merged**
