### PR TITLE
public: rename mathlib to xash3d_mathlib.

### PR DESCRIPTION
**Pull request by nekonomicon**

### CODE REVIEW

**Comment by a1batross** [comment]
Now try to build the menu. :)

**Comment by nekonomicon** [comment]
Need to update menu :)

**Comment by a1batross** [comment]
Didn't noticed other PR. 

While yeah, we have two different mathlibs and this is awful, but menu is more SDK part, which doesn't include libpublic yet.

**Comment by nekonomicon** [comment]
It just breaks compilation of my mdl decompiler, that uses libpublic sources.

**Comment by a1batross** [comment]
Just put public before common includes. 

We need to replace our mathlib(which is derived from Quake's) to common instead. As part of GPL'ed HLSDK headers.

**Comment by a1batross** [comment]
I meant, mv public/mathlib.h common/mathlib.h. 

I don't like this but what can we do? menu is meant to be built with both engine sources and SDK without a line of change.

**Comment by nekonomicon** [comment]
Done.

**Comment by a1batross** [comment]
I'm fine with that. 

@mittorn ?

**Comment by mittorn** [comment]
common/mathlib.h is quake mathlib that used by sdk exports, public/mathlib.h is part of libpublic. It's better to rename public mathlib to xash3d_mathlib

**Comment by nekonomicon** [comment]
>It's better to rename public mathlib to xash3d_mathlib

Done.

**Pull request merged**
