### PR TITLE
Update sv_game.c

### PR DESCRIPTION
**Pull request by KayvK**
Fixes obscure compile error because MAP_ANONYMOUS is deprecated

### CODE REVIEW

**Comment by a1batross** [comment]
I see it's a synonym in man page for mmap. But when it doesn't compile?

**Comment by KayvK** [comment]
> I see it's a synonym in man page for mmap. But when it doesn't compile?

GCC wasn't happy with it on Ubuntu. Changing it from MAP_ANONYMOUS to MAP_ANON fixed the errors and the rest of the compile went smoothly.

**Comment by a1batross** [comment]
Strange, it's fine on my computer. Also using Ubuntu.

**Comment by a1batross** [comment]
Superseded by https://github.com/FWGS/xash3d-fwgs/commit/5678d9a2533bfc92011dbaadc23e963cc0a50f85

**Pull request closed without merging**
