### PR TITLE
engine/wscript: Add --default-accelerated-renderer

### PR DESCRIPTION
**Pull request by glebm**
Refs #247

### CODE REVIEW

**Comment by mittorn** [comment]
Do we really need this in build system? When GL render is disabled, engine will fallback to GLES.
The reason of your issue is that GL was enabled, failed to initialize, ahd fallback failed because of broken unintitalization.
On special targets you may define it in defaults.h

**Comment by glebm** [comment]
> When GL render is disabled, engine will fallback to GLES.

Are you sure? It does not do this

**Comment by glebm** [comment]
Was replying from phone, a more detailed explanation about why it does not fall back to GLES is here: https://github.com/FWGS/xash3d-fwgs/issues/247#issue-775118991

**Comment by a1batross** [comment]
Sorry it took me whole day to reply. :)

I think we need to rework fallback code, that will check availability of gl, then gles, then gles2, then gl4es renderer and end at software renderer.

We don't really want to give any new build-time options anymore.

**Comment by mittorn** [comment]
Ok, it does not really fallback to gles, only to soft
But separate option is not good idea here.
macro only shpuld be set when user disables gl renderer in build-time, but gles renderer enabled. Or rework fallback code like a1batross proposed

**Comment by glebm** [comment]
I do agree with both of these suggestions. Will someone more familiar with the code be willing to implement them?

**Comment by glebm** [comment]
I'm trying to figure out at least the waf build (never worked with waf before)

**Comment by glebm** [comment]
OK I think I've figured out the `waf` part: https://github.com/FWGS/xash3d-fwgs/pull/257
I'll leave the runtime part to someone more familiar with the way things are done around here

**Pull request closed without merging**
