### PR TITLE
Backport NAT bypass feature from 0.19

### PR DESCRIPTION
**Pull request by SNMetamorph**

### CODE REVIEW

**Comment by SNMetamorph** [comment]
Not ready for merge

**Comment by SNMetamorph** [comment]
So it's tested, it works, and ready for merge IMO

**Comment by SNMetamorph** [comment]
@a1batross @nekonomicon

**Review by a1batross — APPROVED** [review]

**Comment by a1batross** [comment]
Looks clean enough to me.

**Pull request merged**
