### PR TITLE
Double promotion fixes

### PR DESCRIPTION
**Pull request by a1batross**
Left for open discussion, as most of these changes may directly affect precision.

### CODE REVIEW

**Comment by a1batross** [comment]
```
$ cat test.c 
#include <stdio.h>
#include <math.h>

void main( void )
{
        double dbl = M_PI * 123.123f;
        float fl = (float)M_PI * 123.123f;

        printf("%f\n", dbl);
        printf("%f\n", fl);
}

$ ./a.out 
386.802316
386.802338

```

**Comment by nekonomicon** [comment]
Seems tgmath.h header broken on FreeBSD :(
It does not work correctly for sin/cos.
https://wiki.freebsd.org/Numerics

**Comment by a1batross** [comment]
@nekonomicon can you check if tgmath test solves compiling problem on FreeBSD?

**Comment by a1batross** [comment]
If yes, I'm gonna merge fdp into master.

**Comment by nekonomicon** [comment]
clang not pass test and -Werror=implicit-function-declaration breaks build.
gcc could not finish configuring build at all.

**Comment by a1batross** [comment]
@nekonomicon post build log and config.log, please.

**Comment by nekonomicon** [comment]
gcc:
https://pastebin.com/njCsmGrQ
```
root@cyberdog:/usr/ports/games/xash3d_fwgs # make
===>   xash3d_-0.20 depends on file: /usr/local/bin/python2.7 - found
===>   xash3d_-0.20 depends on file: /usr/local/bin/sdl2-config - found
===>   xash3d_-0.20 depends on shared library: libSDL2.so - found (/usr/local/lib/libSDL2.so)
===>  Configuring for xash3d_-0.20
Setting top to                                          : /usr/ports/games/xash3d_fwgs/work/xash3d-fwgs-6a5ddc7 
Setting out to                                          : /usr/ports/games/xash3d_fwgs/work/xash3d-fwgs-6a5ddc7/build 
Build type                                              : release 
Checking for 'clang' (C compiler)                       : not found 
Checking for 'gcc' (C compiler)                         : gcc8 
Target OS                                               : freebsd 
Target CPU                                              : x86 
Target binfmt                                           : elf 
Checking for 'clang++' (C++ compiler)                   : not found 
Checking for 'g++' (C++ compiler)                       : g++8 
Target OS                                               : freebsd 
Target CPU                                              : x86 
Target binfmt                                           : elf 
Checking git hash                                       : no 
Checking for program 'strip'                            : /usr/bin/strip 
Checking if 'gcc' can target 32-bit                     : no 
Checking for library SDL2                               : yes 
Checking for library SDL2 sanity                        : no 
Checking for required C flags                           : no 
The configuration failed
(complete log in /usr/ports/games/xash3d_fwgs/work/xash3d-fwgs-6a5ddc7/build/config.log)
===>  Script "configure" failed unexpectedly.
```

clang:
https://pastebin.com/9AiEmvQ3
https://pastebin.com/EgV9raDL

**Comment by a1batross** [comment]
>-Wsometimes-uninitialized

wtf is sometimes-uninitialized? Is it passed through CFLAGS envvar?

Try to build with clang again. I explicitly undefined HAVE_TGMATH_H if test was failed and rebased branch on latest master.

**Comment by nekonomicon** [comment]
>wtf is sometimes-uninitialized? Is it passed through CFLAGS envvar?
Ah... Yep, It's my mistake.

**Comment by nekonomicon** [comment]
```
root@cyberdog:/usr/ports/games/xash3d_fwgs # make
===>   xash3d_-0.20 depends on file: /usr/local/bin/python2.7 - found
===>   xash3d_-0.20 depends on file: /usr/local/bin/sdl2-config - found
===>   xash3d_-0.20 depends on shared library: libSDL2.so - found (/usr/local/lib/libSDL2.so)
===>  Configuring for xash3d_-0.20
Waf: The wscript in '/usr/ports/games/xash3d_fwgs/work/xash3d-fwgs-60681f0' is unreadable
Traceback (most recent call last):
  File "/usr/ports/games/xash3d_fwgs/work/xash3d-fwgs-60681f0/.waf-2.0.18-bf90c9fee0a86d75f6094da72c234ee5/waflib/Scripting.py", line 102, in waf_entry_point
    set_main_module(wscript)
  File "/usr/ports/games/xash3d_fwgs/work/xash3d-fwgs-60681f0/.waf-2.0.18-bf90c9fee0a86d75f6094da72c234ee5/waflib/Scripting.py", line 142, in set_main_module
    Context.g_module=Context.load_module(file_path)
  File "/usr/ports/games/xash3d_fwgs/work/xash3d-fwgs-60681f0/.waf-2.0.18-bf90c9fee0a86d75f6094da72c234ee5/waflib/Context.py", line 362, in load_module
    exec(compile(code,path,'exec'),module.__dict__)
  File "/usr/ports/games/xash3d_fwgs/work/xash3d-fwgs-60681f0/wscript", line 238
    msg='Checking if tgmath.h is usable', mandatory=False):
```

**Comment by a1batross** [comment]
@nekonomicon I've fixed that trailing colon. :)

Also, seems I figured out how to run freebsd builds on cirrus ci.

**Pull request merged**
