### PR TITLE
engine: client: enable interpolation of local player angles

### PR DESCRIPTION
**Pull request by SNMetamorph**
To look player model in third person look smooth

### CODE REVIEW

**Comment by a1batross** [comment]
I'm sure it will break something else, since it modifies both origin and angles.

**Comment by SNMetamorph** [comment]
Otherwise, in that case origin will be overwritten with subsequent code. The only thing I can suggest is make functions that doesn't modify entity state to pass in const cl_entity_t pointer

**Comment by SNMetamorph** [comment]
I tested this and it's ok. Angles are interpolated, but origin didn't affected at all

**Comment by a1batross** [comment]
It's not about const or not. And you added const modifier where I didn't asked to and half of the patch is ugly casts now.

Updating angles from interpolated data is just unnecessary by design. This is local data, angles can be easily taken from input for example. That's IF we're actually turning to same direction we're looking into. I think it can be up to client.dll to interpolate angles or calculate them from input.

Nonetheless, I approve this patch anyway. But please, update your patch to be minimal as possible.

**Comment by SNMetamorph** [comment]
> It's not about const or not. And you added const modifier where I didn't asked to and half of the patch is ugly casts now.
> 
> Updating angles from interpolated data is just unnecessary by design. This is local data, angles can be easily taken from input for example. That's IF we're actually turning to same direction we're looking into. I think it can be up to client.dll to interpolate angles or calculate them from input.
> 
> Nonetheless, I approve this patch anyway. But please, update your patch to be minimal as possible.

Ok

**Review by a1batross — APPROVED** [review]

**Pull request merged**
