### PR TITLE
engine: client: added API for GoldSrc Monitor

### PR DESCRIPTION
**Pull request by SNMetamorph**

### CODE REVIEW

**Comment by a1batross** [comment]
Well, I'm glad you're extending engine on your own needs, we're all doing that.

But how about using existing APIs? Like, you can extend our MobilityAPI or RenderAPI, what fits better in your opinion. For example, SPR_Load already present in RenderAPI. SPR_Frames present in normal client interface.

I'm not exactly sure how GSMon works, in my opinion it should wrap client.dll. Doing so carefully will never cause problems with compatibility.

**Comment by SNMetamorph** [comment]
The problem is GoldSrc Monitor does not proxying client.dll and therefore can't use any on this APIs. 
Instead of proxying client.dll, tool injects in game and search for client engine functions. This solution used to avoid modifying game files and it's just more convenient for user.

**Comment by a1batross** [comment]
Then both SPR_Frames and SPR_LoadExt must be set as exports instead. Anyway, they are already part of another APIs and shouldn't drastically change.

**Comment by SNMetamorph** [comment]
Ok I did it

**Pull request merged**
