### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by a1batross**
@mittorn @nekonomicon 

Please review it, I will squash-merge it after README will be done.

### CODE REVIEW

**Comment by nekonomicon** [comment]
Looks good.

**Comment by BlackPhrase** [comment]
It looks like you wanna throw in a bunch of new features in it, so I have a couple of questions to you:
1) Is it worth maintaining the thing in 2018?
2) How much is the popularity of this and the main engine repos?
Why I wanna know that is because looking at the community makes me feel that it's simply dead

**Comment by a1batross** [comment]
Let me explain what this repository means. 
Unkle Mike has significantly updated the engine, so updating Xash3D FWGS would be just too hard. I thought, that it can be better to re-boot the fork, without keeping bad solutions we did in 2015-2016. So this repo if referred as "New Engine" and FWGS/xash3d as "Old Engine".

1. It's not worth to maintain "Old Engine" at first. It's codebase grown up too much than I thought it can be in the end of 2014. 
At second, Unkle Mike started working on engine again, bringing new features, deprecating old. Also he started to accept FWGS patches for multiplayer and GoldSrc compatibility.

Community isn't dead. Original engine has it's own community of mod/game makers and we have our user base, which interested only on Android port. I personally don't like that situation. We also need mod or game makers to know how we should improve the engine. 

2. New engine will completely replace old engine once. It means that old engine will not receive updates, will not show servers anymore. Xash3D FWGS stays Xash3D FWGS. Consider this as a huge update.

**Comment by BlackPhrase** [comment]
Yep, I noticed that back in a 38xx build update
You did a lot of work maintaining the engine during all these 4 years

But using the original HLSDK is not a recommended thing by me
https://www.moddb.com/mods/half-life-subtitles-mod/news/sad-news-legal-issues-lack-of-time
Valve banned the mod simply because the SDK was used to create a mod not for the original GS (as stated in EULA)
That fact keeps a lot of developers away from making a mod on the reimplemented engine
I did rewrite major parts of the SDK myself during the year using the original Quake code to keep it clean and out of Valve authority and their stupid EULA

Well, yes, original engine community is not so dead, but when things are related to reimplementing the original engine it really feels like that, even if it could provide a lot more features that the original, everyone stays silent

**Comment by a1batross** [comment]
Ah, you that Subtitles MOD author! 

I think Valve really don't care about GoldSrc. They won't allow Xash3D Half-Life mods on Steam, obviously, but GoldSrc compatibility in Xash3D exists for 8 years already and engine is opensource for 7 years. If they wanted to release their copyright dogs, then maybe they already did that. But in reality no one from Valve tried to get in contact with Xash3D or ReHLDS developers.

Didn't knew about your SDK. Will look out! :)
@mittorn also tried to reimplement SDK using only Quake structures, but it's too far from complete state.

**Comment by BlackPhrase** [comment]
>>Ah, you that Subtitles MOD author!
Oh, no. It's this guy:
https://github.com/Fograin

>>I think Valve really don't care about GoldSrc

I partially agree with you, but:
https://www.moddb.com/mods/half-life-subtitles-mod/news/sad-news-legal-issues-lack-of-time
> Well, even worse, I can't release it on greenlight, but also I might get in trouble by releasing it on moddb.com or any other place. Valve said that they might (and mostly will) take legal actions against it and they will take it down. They also gave me all contact info for theirs attorney, if I want to get more detailed info.

>>Upd: can't find. Where is it?
https://github.com/headcrab-junkyard/ogs-sdk
I manually retyped some headers instead of copy-pasting them from the original SDK
But as I mentioned, it's not fully compatible with your or original GS because it's for OGS and OGS simply doesn't have support for some of the things that Valve implemented in GS (the supporting code is non-existent at this point)

**Comment by mittorn** [comment]
Maybe ./waf if waf distributed with engine?

**Comment by a1batross** [comment]
I think, even if it will be copypaste, it must be separated for Windows and *nix. 

In *nix we do `./waf` or `python waf`, in Windows we do just `waf`, because waf.bat. And a note about msvs generator.

**Comment by mittorn** [comment]
Is c:/path/to/SDL2 valid path on windows?
I dont think many people use posix shell on win32

**Comment by mittorn** [comment]
>Even if Xash3D FWGS does support targetting 64-bit, anything can happen, not to mention that you can't load games without recompiling them from source code!
It support 64bit now, it "anythong can happen" actual?
Maybe better warn user about stability issues (i catched one segfault and failed to debug it)

**Comment by mittorn** [comment]
i am not about compatibility, just about "Anything can happen"

**Pull request merged**
