### PR TITLE
Reject Connection on Undefined Protocol

### PR DESCRIPTION
**Pull request by bariscodefxy**

### CODE REVIEW

**Comment by a1batross** [comment]
What's the problem? If version is 0, then it will not pass version != PROTOCOL_VERSION anyway.

**Comment by bariscodefxy** [comment]
> What's the problem? If version is 0, then it will not pass version != PROTOCOL_VERSION anyway.

Safety is paramount.

**Comment by lewa-j** [comment]
Current PROTOCOL_VERSION is 49. So it will reject any version expept 49. It includes 0.

**Comment by a1batross** [comment]
> > What's the problem? If version is 0, then it will not pass version != PROTOCOL_VERSION anyway.
> 
> Safety is paramount.

Can you show an example where 0 != 49 passes the check?

**Comment by bariscodefxy** [comment]
> > > What's the problem? If version is 0, then it will not pass version != PROTOCOL_VERSION anyway.
> > 
> > 
> > Safety is paramount.
> 
> Can you show an example where 0 != 49 passes the check?

No :D

**Pull request closed without merging**
