### PR TITLE
ref: disabled verbose reporting about tracer invalid color index

### PR DESCRIPTION
**Pull request by SNMetamorph**
Fixes messages spamming in mods such as Sven Co-op 4.8

### CODE REVIEW

**Comment by a1batross** [comment]
What's the point of this? Why not to turn it into DPrintf or Reportf, if it's bothering you?

We still have bugs like #388 and it won't fix the issue for them, just like it less noticeable and harder to debug.

**Comment by SNMetamorph** [comment]
> We still have bugs like #388 and it won't fix the issue for them, just like it less noticeable and harder to debug.

It's not fixable from engine side, because this is bug of mod itself. GoldSrc does not any validation of color index, but still have buffer with 12 colors just like as we have. Therefore, any index above 12 will cause undefined behavior in such cases, while no reporting anything about invalid color index. This PR clarifies behavior in such cases, and fixes not reason, but consequences of #388

**Comment by a1batross** [comment]
So you're telling GoldSrc just reads whatever is out of bounds color array and interprets as an RGB...

Still, it would be nice to have such message for mod developers at higher dev level, though it might be better to catch it not when it draws, because it will be printed each frame, but when it creates. Then it should be in cl_efx.c. Also, I don't think we will increase tracers color set anyway, as there is no real reason for this for now. :)

**Comment by SNMetamorph** [comment]
> So you're telling me, GoldSrc just reads whatever is out of bounds color array and interprets as an RGB...

Exactly. In function `R_DrawParticles`:
изображение

**Comment by SNMetamorph** [comment]
> Still, it would be nice to have such message for mod developers at higher dev level, though it might be better to catch it not when it draws, because it will be printed each frame, but when it creates

Yes, this is good idea. But somehow we should have option to disable these messages for mods that won't be fixed anyway because they was abandoned.

**Comment by a1batross** [comment]
I'll merge it for now, restoring the message might be done later.

GoldSrc seems to print it only in R_UserTracerParticle impl.

**Comment by a1batross** [comment]
I wonder if we could replicate the broken values that GoldSrc from those versions had. If they don't get changed, of course.

**Pull request merged**
