### PR TITLE
some dead code elimination

### PR DESCRIPTION
**Pull request by iZarif**

### CODE REVIEW

**Comment by a1batross** [comment]
Never do this. 

At first, you're doing it wrong, potentially breaking compatibility and protocol.
At second, some dead code has logical meaning or just for readability.
At third, actual dead code will be removed by compiler without breaking for us.

Also, for future PRs, if your commit touch different modules(in this case three of them), split it into smaller commits.

**Comment by iZarif** [comment]
Why did you close this PR?

"you're doing it wrong, potentially breaking compatibility and protocol."

Maybe, but I could fix it.

"some dead code has logical meaning or just for readability."

My changes did not impair readability at all.

"dead code will be removed by compiler without breaking anything for us"

It's silly to rely on the compiler, maybe not in this particular case but still.

"if your commit touch different modules(in this case three of them), split it into smaller commits."

Ok.

**Comment by a1batross** [comment]
>Maybe, but I could fix it.

Ok, then please, re-read your changes and decide what's was going wrong. I explained you in a chat.

>It's silly to rely on the compiler, maybe not in this particular case but still.

It isn't. Compilers nowadays are way smarter than humans.

**Comment by a1batross** [comment]
>My changes did not impair readability at all.

Look into cl_main.c:831. You removed the obviously copypasted line `i = cls.netchan.outgoing_sequence & CL_UPDATE_MASK;` but not the comment. So... look at the uglyness you left: https://github.com/iZarif/xash3d-fwgs/blob/8fbd3ead93e11ffbd341abd5c05fbb1b2b97ad1e/engine/client/cl_main.c#L831.

Look here: https://github.com/iZarif/xash3d-fwgs/blob/8fbd3ead93e11ffbd341abd5c05fbb1b2b97ad1e/ref_gl/gl_triapi.c#L331. You left empty switch-case. Are you serious? 

Also, in same file, in function `CL_FixupColorStringsForInfoString` you removed `count += 2`. Why? You know that this function works only with infostrings? You know, you made this code to overrun the buffer? If you want to fix it, make it work with specified buffer size, not the hardcoded MAX_INFOSTRING. 

You just don't know nothing about the code you're tried to _fix_. That's why I'm closed it. 

You did nothing but broke the engine. And you want me to explain you? Nah, I have **better things to do than explaining obvious shit that you don't want to notice**.

**Comment by a1batross** [comment]
@nekonomicon 

ok, show the example. I did a simple one: https://godbolt.org/z/2AggP3, as you see, compiler removes useless even on -O1.

**Comment by nekonomicon** [comment]
@a1batross wat?

https://godbolt.org/z/e3ko4u

**Comment by iZarif** [comment]
@a1batross 
"So... look at the uglyness you left"
I could fix it.

"You left empty switch-case. Are you serious?"
Did anyone die because of this?

"Also, in same file, in function CL_FixupColorStringsForInfoString you removed count += 2"
My mistake, but it can be fixed too.

"You just don't know nothing about the code you're tried to fix."
It's not easy to figure out someone else's code

"obvious shit that you don't want to notice"
Why do you think that I don't want to notice this "'obvious' shit"?

"I have better things to do"
I have them too, but I spent my personal time and sincerely wanted to improve the project. 
And you are the project’s maintainer and should have pointed out to me at least a couple of mistakes and not yell "you're doing it wrong"

**Comment by Solexid** [comment]
@iZarif 

> It's not easy to figure out someone else's code
Maybe on this line you should stop and do some research about project, before  flood it with meaningless commit/s?

**Comment by iZarif** [comment]
@Solexid 

"before flood it with meaningless commit/s"

Maybe, the problem is that I don't know what's not meaningless for the project.
In my opinion code refactoring is always "meaningfull" (even though I screwed up this time)

**Comment by Solexid** [comment]
@iZarif 
Ладно, надоел уже этот фарс. Давай объясню на понятном тебе языке, потому что ждать по пол часа как ты формулируешь фразу, надоело. 
Чтобы писать в серъёзный проект, нужно его серъёзно изучить. Если твой первый шаг в проекте, это попытка пропихнуть непроверенный, непротестированный и неизвестно как работающий код - не удивляйся что твой пр отбили. Скажи спасибо что Алибек тебе ответил, а не просто молча закрыл реквест. Тебе уже объяснили в чем дело, твой выбор - либо продолжать нести чушь и получить запрет доступа как таковой, либо успокоится, изучить проект, и сделать то что ты хотел ПРАВИЛЬНО, уже в новом пулл реквесте.

**Comment by iZarif** [comment]
@Solexid Какой фарс? Просто хотел внести немного ясности. Мог остановиться на любом сообщении это вы продолжаете мне отвечать. И что за вывод на пустом месте про "понятный мне язык"? Тебе до моего языка расти ещё надо а не падать. Алибеку спасибо тоже не за что говорить он в целом по своей воле отвечал. По крайней мере я рядом с ним с паяльником в руках не стоял.

**Comment by a1batross** [comment]
>It's not easy to figure out someone else's code

Будто из-за того, что тебе сложно разобраться, я сразу должен принимать любые патчи. 

Нет, я сразу выразил свою точку зрения о твоей безграмотности. Несогласен? Можешь закрыть дверь снаружи.

**Comment by a1batross** [comment]
> Why do you think that I don't want to notice this "'obvious' shit"?

Я тебе уже объяснил всё днем в первый раз и во второй раз, сейчас, у меня никакого другого предложения кроме сходить нахуй нет.

**Comment by Solexid** [comment]
@iZarif 
>Тебе до моего языка расти ещё надо а не падать

Ясно, видимо русский язык для тебя тоже не понятен, раз ты вообще не понял о чем речь. На этом я думаю можно закончить.

**Comment by iZarif** [comment]
> Будто из-за того, что тебе сложно разобраться, я сразу должен принимать любые патчи.

Если ты не заметил я тебя не просил проталкивать мой патч, это ты сам навыдумывал потому что не тем местом читаешь.

**Comment by iZarif** [comment]
> Ясно, видимо русский язык для тебя тоже не понятен,

Ты тут начал про понятный мне язык писать из-за того что сформулировать на английском не можешь. Это очевидно.

**Pull request closed without merging**
