### PR TITLE
Add support for MP3 looping through custom ID3v2 tagging

### PR DESCRIPTION
**Pull request by a1batross**
Highly experimental

### CODE REVIEW

**Comment by a1batross** [comment]
Forgot to support de-unsynching tag frames.

**Comment by SNMetamorph** [comment]
@CASPERX69XSOFT tested it with ambient_generic, and it doesn't works. Link to looped file: https://disk.yandex.ru/d/5VjnGQ2VDUiVxA

**Comment by a1batross** [comment]
So it turns out ID3v2.3 doesn't actually support UTF-8.

In engine, we explicitly drop UTF-16 tags. Gonna go back and enforce 2.4 only.

**Comment by SNMetamorph** [comment]
So, what's next? We got it to work

**Comment by a1batross** [comment]
Well, the comments in this PR is basically a TODO.

At this point I want to add:
* Very basic support for UTF-16 tags. Because tags we are using have only basic latin characters, I can do just memcmp(), and simple atoi for UTF-16.
* Unsynchornisation support, this is very important, as it can be automatically added by ID3 encoders, and may be not possible to disable.
* Add an example on how to work with mp3tag.

**Comment by a1batross** [comment]
I will merge this as is, if somebody has time to add example for mp3tag, send a patch.

**Pull request merged**
