### PR TITLE
engine: client: in_touch.c: add spray button.

### PR DESCRIPTION
**Pull request by nekonomicon**

### CODE REVIEW

**Comment by a1batross** [comment]
Can you attach a screenshot?

**Comment by Vladislav4KZ** [comment]
Where the ``touch_default/spray`` button texture itself?

**Comment by a1batross** [comment]
@Vladislav4KZ https://github.com/FWGS/xash-extras/pull/16

there is a proposed image

**Comment by Vladislav4KZ** [comment]
> https://github.com/FWGS/xash-extras/pull/16
> 
> there is a proposed image

Ok, I didn't see the notification for this pull request on Discord

**Pull request merged**
