### PR TITLE
engine: client: in_touch.c: make the voicechat and spray buttons multiplayer only

### PR DESCRIPTION
**Pull request by Vladislav4KZ**
# Singleplayer touch layout
singleplayer_touch_layout

# Multiplayer touch layout
multiplayer_touch_layout

Screenshots are taken in 1280x720 resolution

### CODE REVIEW

**Comment by DavidMacalister** [comment]
Nice

**Comment by Vladislav4KZ** [comment]
# Singleplayer touch layout
singleplayer_touch_layout

# Multiplayer touch layout
multiplayer_touch_layout

Screenshots are taken in 1280x720 resolution

**Comment by SNMetamorph** [comment]
> Nice

Are you the one who's strugging with voice chat several days ago?

**Comment by DavidMacalister** [comment]
> > Nice
> 
> Are you the one who's strugging with voice chat several days ago?

No

**Pull request merged**
