### PR TITLE
Refapi 5

### PR DESCRIPTION
**Pull request by a1batross**
Main RefAPI changes:

- Removed GetSomethingByIndex calls, renderers are supposed to cache pointer values
- Removed previously unused calls
- Simplified remapping calls
- GetRefAPI now must return REF_API_VERSION

API simplification gave a small performance boost: from 1350 to 1450 FPS in a small timedemo test.

This is an old branch that I decided to continue on after having an idea about remap calls. It doesn't have vbo-fix changes yet but I expect to merge these after this branch will be merged.

### CODE REVIEW

**Comment by a1batross** [comment]
pls review

cc @mittorn @SNMetamorph @nekonomicon @Velaron

**Comment by a1batross** [comment]
also

cc @w23

**Comment by SNMetamorph** [comment]
Looks good to me

**Comment by a1batross** [comment]
Year 2023.
GitHub can't detect rebases yet.

**Pull request closed without merging**
