### PR TITLE
Fixed TriAPI WorldToScreen behavior to match GoldSrc

### PR DESCRIPTION
**Pull request by SNMetamorph**
Tested
@a1batross

### CODE REVIEW

**Comment by a1batross** [comment]
Seems fine to me. 

But since we don't need TriWorldToScreen wrapper, can you get rid of it? See CL_FillTriAPIFromRef function in ref_common.c file.

**Comment by SNMetamorph** [comment]
Ok why not

**Comment by SNMetamorph** [comment]
I have looked and not sure should I do that or not. Because TriWorldToScreen is widely used across all code, therefore I should remove all this references and it causes many file changes. Is it worth it?

**Comment by a1batross** [comment]
It can be separate patch then, thanks!

**Pull request merged**
